### ISSUE TITLE
Fails to build with ruby 2.5?

### ISSUE THREAD

**Issue by Keruspe** [crypto-rb/rbnacl-libsodium#25]
Hi,

Not sure if it's strictly ruby 2.5 related but I started experiencing issues at the time I updated it.

```
TypeError: no implicit conversion of nil into String
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:23:in `join'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:23:in `<module:Libsodium>'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:4:in `<module:RbNaCl>'
.bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons/raw_macaroon.rb:3:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons/raw_macaroon.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons/macaroons.rb:3:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons/macaroons.rb:3:in `<top (required)>'
.bundle/gems/macaroons-1.0.0/lib/macaroons.rb:1:in `require'
.bundle/gems/macaroons-1.0.0/lib/macaroons.rb:1:in `<top (required)>'
```

**Comment by andy-plutoflume** [comment]
We're seeing this when using this inside alpine

**Comment by HorizonShadow** [comment]
So the reason you're getting that first error is because libsodium.rb is way back on https://github.com/crypto-rb/rbnacl-libsodium/blob/fb8bfb6f20151dfa4fd6d9ee005d3fd6bdb00f62/lib/rbnacl/libsodium.rb

You can fix it by manually replacing .bundle/gems/rbnacl-libsodium-1.0.16/lib/rbnacl/libsodium.rb with this: https://raw.githubusercontent.com/crypto-rb/rbnacl-libsodium/master/lib/rbnacl/libsodium.rb
